development:
  clients:
    default:
      database: local
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: covid_monitoring_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
